### ISSUE TITLE
Elaborate a bit about the IDT when Pure64 is used

### ISSUE THREAD

**Issue by kirbyfan64** [ReturnInfinity/Pure64#25]
From what I've seen in BareMetal's source, Pure64 sets up some kind of IDT starting at memory address 0.

I've tried various things, and none of them work. It would be VERY helpful if there a document somewhere explaining how this works.

**Comment by rzhikharevich** [comment]
Your ultimate guide for this: http://wiki.osdev.org/Main_Page

**Comment by kirbyfan64** [comment]
@rzhikharevich I know about OSDev. It's that Pure64 seems to do something special with the IDT that BareMetal uses, and I don't see it documented anywhere, even OSDev.

**Comment by IanSeyler** [comment]
Could be due to it being a 64-bit IDT. I'll dig up what I can.

**Comment by IanSeyler** [comment]
From the comments in Pure64 (so glad I've been on top of commenting the code!)

Each IDT entry is 16 bytes (128 bits) in size:

16-bit : low word of handler address (bits 15..0)
16-bit : code selector from GDT
16-bit : 0x8E00 - Gate marker
16-bit : high word of the handler address (bits 31..16)
32-bit : extra high dword of the handler address (bits 63..32)
32-bit : 0 - Reserved value

Entries 0 thru 31 are mapped for CPU exceptions.. everything else is mapped to interrupt handlers.

What is it that you are trying to do?

**Comment by kirbyfan64** [comment]
I'm writing everything in a toy language I found, so here's a rough translation to C:

```c
void outb(uint16_t port, unsigned char data);
unsigned char inb(uint16_t port);

void install_gate(void* f, uint64_t g) {
    g <<= 4;
    *((uint16_t*)g) = (uint16_t)f;
    g += 16+4;
    *((uint16_t*)g) = (uint16_t)f >> 16;
    g += 16;
    *((uint32_t*)g) = (uint32_t)f >> 32;
}

void clear_mask(unsigned char m) {
    uint16_t port;
    unsigned char bit = m,
                            omask;
    if (m < 8) port = 0x21;
    else {
        port = 0xA1;
        bit -= 8;
    }
    omask = inb(port) | (1 << bit);
    outb(port, omask);
}

void init() {
    // ...
    install_gate(keyboard_w, 0x21);
    clear_mask(0x01);
    clear_mask(0x02);
    clear_mask(0x08);
    // ...
}
```

with my assembly file like this:

```
extern vidptr

global inb
global outb
global keyboard_w

keyboard_w:
  mov byte [vidptr], '!'
  mov byte [vidptr+1], '!'
  mov byte [vidptr+2], '!'
  mov byte [vidptr+3], '!'
  t: jmp t ; infinite loop

inb:
  mov dx, [rsp+4]
  in al, dx
  ret

outb:
  mov dx, [rsp+4]
  mov al, [rsp+6]
  out dx, al
  ret
```

I got most of the stuff involving gates and masks from the BareMetal source code. I thought this would work, but nothing happens when I press a key. At all.

Again, I've looked stuff up, but I haven't found anything, unless I'm missing something blatantly obvious.

**Comment by IanSeyler** [comment]
Have you tried debugging in Bochs to see if the interrupt gate is being built properly?

**Comment by kirbyfan64** [comment]
@IanSeyler Whoops, forgot about this. I checked, and it looks like it is. I'm going to try to rewrite that portion in C to check if I've encountered a compiler bug.

**Comment by kirbyfan64** [comment]
Definitely not a compiler bug; using C still doesn't work.

**Comment by IanSeyler** [comment]
Can you provide the code you're using? I'm in the process of re-writing the BareMetal kernel in C but haven't tried interrupts yet.

**Comment by kirbyfan64** [comment]
@IanSeyler https://github.com/kirbyfan64/mk64
