### ISSUE TITLE
Memory Map - `BSP_IP` is a 16 bit value (not 32 bit)

### ISSUE THREAD

**Issue by lmartinking** [ReturnInfinity/Pure64#26]
I've just been poking at the Info Table at 0x5000, and discovered while mapping it to a struct that BSP_ID is a 16 bit value. The address/offset is correct, but the width is incorrect in the documentation.

![screen shot 2015-11-13 at 2 49 48 pm](https://cloud.githubusercontent.com/assets/38818/11138399/ddf4b92e-8a15-11e5-9ecf-e6c8a4a79384.png)

**Comment by IanSeyler** [comment]
The reserved space for the BSP_ID value is 32-bit. Currently the APIC ID will usually be an 8-bit number. With x2APIC this will increase so this is for future-proofing.

**Comment by lmartinking** [comment]
Thanks for the clarification Ian!
