### ISSUE TITLE
New Fs

### ISSUE THREAD

**Issue by gp7485451** [ReturnInfinity/Pure64#31]
1. Ext4 is faster than Fat12, Fat16 and Fat32.
2. Ext4 supports 16 Terabyte files and 1 Exabyte volumes.
3. Fat32 only supports 4 Gigabyte files, and 8 Terabyte volumes. (And the rest of the File Allocation Table Versions are even lower)
4. Extended filesystems has higher file and volume capacity than File Allocation Tables.
5. Also, Extended filesystems beats File Allocation Tables in speed.

Check out ZFS, it is even better then all of them. Source:
https://en.wikipedia.org/wiki/Comparison_of_file_systems

**Comment by IanSeyler** [comment]
Pure64 does not rely on any file system directly. This is up to the boot sector and the payload that Pure64 starts after it has completed initialization of the machine.
