### ISSUE TITLE
will hang up when rebooting the 3rd time

### ISSUE THREAD

**Issue by ustime** [ReturnInfinity/Pure64#36]
running in qemu, the os can only be rebooted 2 times using the reboot command without qemu virtual machine being powered off. the third time of rebooting will cause the system hang up in 'starting the kernel ...'.

also, it seemed cpu counter is not reset, causing cpu number keep increasing across reboot.

**Comment by IanSeyler** [comment]
Added code to clear out the info table area before the table is built.

Thanks for creating an issue for this bug!
