### ISSUE TITLE
Graphics mode

### ISSUE THREAD

**Issue by IanSeyler** [ReturnInfinity/Pure64#41]
Start the system in graphics mode and ditch text mode.

This is required for UEFI as there is no text mode anymore. A linear frame buffer should be configured on bootup and that information (memory address, resolution, color depth) should be stored in the infomap.

The BareMetal kernel should start in a serial I/O mode by default. Alloy can then take over the b_output* syscalls.

**Comment by tay10r** [comment]
Currently Pure64 gives the video base address, horizontal and vertical resolutions and color depth.

It would be nice to know the horizontal and vertical padding, if there is any, to avoid running into problems later.

It would also be good to know the physical size of the screen. FreeType can use that information to render the font faces better. It's also basically a requirement for 4K screens. On a 4K screen, without the physical screen size, the fonts are going to appear extremely small.

I'm not sure if these requests or trivial or not to support, but so far I regard them as non-urgent.

**Comment by IanSeyler** [comment]
This work has been completed and Alloy is working in graphics mode thanks to the work by @tay10r.
