### ISSUE TITLE
Could Pure64 fit on a floppy disk? (maybe 2.88 MB if can't to 1.44 MB)

### ISSUE THREAD

**Issue by informer2016** [ReturnInfinity/Pure64#45]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by tay10r** [comment]
The Pure64 binary, not including the 512-byte bootsector, is only 4096-bytes (or 4KiB). So yes, unless @IanSeyler has additional insight, it can fit into a floppy disk. You can build the project and see for yourself.

**Comment by informer2016** [comment]
Thank you very much for reply, @tay10r although still curious what @IanSeyler would say .
Happy New Year :)

**Comment by IanSeyler** [comment]
Yes, Pure64 could run from a floppy. You would need to write a new bootsector to load Pure64 and the payload into memory. The existing bootsectors are for hard drive and network booting.
