### ISSUE TITLE
Pure64 fails to compile

### ISSUE THREAD

**Issue by makenzi-nzau** [ReturnInfinity/Pure64#72]
Hi!
I'm trying to compile Pure64 using nasm 2.11.08 on ubuntu 16.10 using the `build.sh` script.
This fails with
```
uefi.asm:322: warning: label alone on a line without a colon might be in error
uefi.asm:270: error: invalid combination of opcode and operands
```
Is there any known fix to this?

Thanks!

**Comment by IanSeyler** [comment]
I'll make a proper fix. I think the correct opcode there is `mov`.
