### ISSUE TITLE
Missing mbr.sys

### ISSUE THREAD

**Issue by x444556** [ReturnInfinity/Pure64#77]
When running my build.sh, I receive the message `dd: failed to open 'bin/mbr.sys': No such file or directory`. The docs don't mention how it should be built(at least I couldn't find it) and I couldn't find any file with a name like 'mbr.sys', 'mbr.asm', or similar within the master branch. 

Any help would be appreciated.

Also: I received a warning from nasm regarding line 351 in pure64.asm about a label without a colon. I assume the line should be `retf` instead of `retfq`, correct?

**Comment by IanSeyler** [comment]
I just pulled the current repo and it built without errors. What version of NASM are you using?

**Comment by x444556** [comment]
I just downloaded everything again and now it's working, I don't know what went wrong, but apparently, I'm just stupid. But still thank you for trying to help me.
